version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: notas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - notas_mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # 
    restart: always
    depends_on:
      - mysql
    ports:
      - "5500:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # 
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  notas_mysql_data:
